version: "3.8"

services:
  mongodb:
    image: mongo:6.0
    container_name: kitchensink-mongo
    restart: always
    hostname: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    networks:
      - internal
    ports:
      - "27017:27017"
    volumes:
      - ./mongo/mongo.conf:/etc/mongo/mongo.conf
      - mongodb_data:/data/db
      - ./mongo/certs2:/etc/ssl
    command: ["mongod", "--config", "/etc/mongo/mongo.conf"]

  kitchensink:
    build: .
    container_name: kitchensink-app
    restart: always
    depends_on:
      - mongodb
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@${MONGO_HOST}:${MONGO_PORT}/${MONGO_DB}?authSource=admin&tls=true
      SPRING_PROFILES_ACTIVE: dev
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
    volumes:
      - ./config/certs:/etc/ssl
    ports:
      - "8080:8080"
    networks:
      - internal
  angular-web:
    container_name: angular-web
    image: nginx:1.26.3
    ports:
      - "4200:80"
    volumes:
      - ./nginx/nginx-angular.conf:/etc/nginx/nginx.conf:ro
      - /Users/amitjain/Projects/kitchensink-frontend v2/dist/kitchensink/browser:/usr/share/nginx/html:ro
    restart: always
    networks:
      - internal
  nginx:
    image: nginx:1.26.3
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
      - /Users/amitjain/Projects/kitchensink-frontend/dist/kitchensink-frontend/browser:/usr/share/nginx/html:ro
    depends_on:
      - kitchensink
    restart: always
    networks:
      - internal

volumes:
  mongodb_data:
    driver: local

networks:
  internal:
    driver: bridge
