spring:
  data:
    mongodb:
      uri: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongodb:${MONGO_PORT}/kitchensink?authSource=admin
      auto-index-creation: true
  application:
    name: kitchensink

server:
  port: 8080
  servlet:
    context-path: /api

logging:
  level:
    org:
      springframework:
        security: DEBUG

default:
  password: demo@123
admin:
  email: ${ADMIN_EMAIL}
  password: ${ADMIN_PASSWORD}

management:
  endpoints:
    web:
      base-path: /kitchen-sink/actuator

security:
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    expiration-time: 3600000