spring:
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}
      auto-index-creation: true
  application:
    name: kitchensink

server:
  port: 8080
  servlet:
    context-path: /api

management:
  endpoints:
    web:
      base-path: /kitchen-sink/actuator