spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: kitchensink
      auto-index-creation: true

      username: admin
      password: password
      authentication-database: admin
  application:
    name: kitchen-sink

server:
  port: 8080
  servlet:
    context-path: /api

management:
  endpoints:
    web:
      base-path: /kitchen-sink/actuator